# Generated by Django 3.2.12 on 2023-12-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='image_url',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
