# Generated by Django 3.2.23 on 2024-01-17 09:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Socially', '0003_auto_20240117_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 17, 9, 57, 28, 400272, tzinfo=utc), null=True),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
