# Generated by Django 3.2.23 on 2024-01-17 10:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Socially', '0004_auto_20240117_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 17, 10, 16, 58, 958719, tzinfo=utc), null=True),
        ),
    ]
