# Generated by Django 3.2.23 on 2024-01-17 16:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Socially', '0007_auto_20240117_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 17, 16, 54, 16, 380236, tzinfo=utc), null=True),
        ),
    ]
