# Generated by Django 3.2.23 on 2024-01-18 19:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Socially', '0008_auto_20240117_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 18, 19, 32, 27, 633520, tzinfo=utc), null=True),
        ),
    ]
