# Generated by Django 3.2.23 on 2024-01-19 14:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Socially', '0017_auto_20240119_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 19, 14, 2, 41, 272313, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userjokes',
            name='joke',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
