# Generated by Django 3.2.23 on 2024-01-20 00:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Socially', '0019_auto_20240120_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 20, 0, 39, 43, 751285, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='memes',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='memes',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
